"""add social game content

Revision ID: 8007a17274ed
Revises: a35043d5b08f
Create Date: 2026-09-12 20:52:16.947249
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '8007a17274ed'
down_revision: Union[str, None] = 'a35043d5b08f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('archetype', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=200), nullable=False),
    sa.Column('avatar', sa.String(length=500), nullable=False),
    sa.Column('craft', sa.Integer(), nullable=False),
    sa.Column('focus', sa.Integer(), nullable=False),
    sa.Column('vigor', sa.Integer(), nullable=False),
    sa.Column('will', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('shared_quests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('objective', sa.String(length=300), nullable=False),
    sa.Column('target_days', sa.Integer(), nullable=False),
    sa.Column('current_day', sa.Integer(), nullable=False),
    sa.Column('reward_xp', sa.Integer(), nullable=False),
    sa.Column('reward_embers', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('shared_quest_participants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('shared_quest_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('contribution', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shared_quest_id'], ['shared_quests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shared_quest_id', 'user_id', name='uq_shared_quest_participant')
    )
    op.create_index(op.f('ix_shared_quest_participants_shared_quest_id'), 'shared_quest_participants', ['shared_quest_id'], unique=False)
    op.create_index(op.f('ix_shared_quest_participants_user_id'), 'shared_quest_participants', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shared_quest_participants_user_id'), table_name='shared_quest_participants')
    op.drop_index(op.f('ix_shared_quest_participants_shared_quest_id'), table_name='shared_quest_participants')
    op.drop_table('shared_quest_participants')
    op.drop_table('shared_quests')
    op.drop_table('network_profiles')
    # ### end Alembic commands ###
